//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlythuvienEntities1 : DbContext
    {
        public quanlythuvienEntities1()
            : base("name=quanlythuvienEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETNHAP> CHITIETNHAPs { get; set; }
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<LOAISACH> LOAISACHes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHAPSACH> NHAPSACHes { get; set; }
        public virtual DbSet<PHAT> PHATs { get; set; }
        public virtual DbSet<PHIEUGIAODICH> PHIEUGIAODICHes { get; set; }
        public virtual DbSet<PHIEUSACH> PHIEUSACHes { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAIKHOANDG> TAIKHOANDGs { get; set; }
        public virtual DbSet<TAIKHOANNV> TAIKHOANNVs { get; set; }
        public virtual DbSet<THANHLYHUY> THANHLYHUYs { get; set; }
    }
}
