//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTHUVIENEntities : DbContext
    {
        public QLTHUVIENEntities()
            : base("name=QLTHUVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCGIA> DOCGIAs { get; set; }
        public virtual DbSet<LOAISACH> LOAISACHes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUGIAODICH> PHIEUGIAODICHes { get; set; }
        public virtual DbSet<PHIEUSACH> PHIEUSACHes { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAIKHOANDG> TAIKHOANDGs { get; set; }
        public virtual DbSet<TAIKHOANNV> TAIKHOANNVs { get; set; }
        public virtual DbSet<THANHLYHUY> THANHLYHUYs { get; set; }
    }
}
