//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAODICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUGIAODICH()
        {
            this.PHIEUSACHes = new HashSet<PHIEUSACH>();
        }
    
        public string MAPHIEU { get; set; }
        public string MADG { get; set; }
        public string LOAIPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYMUON { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<decimal> PHIPHATSINH { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUSACH> PHIEUSACHes { get; set; }
    }
}
