//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANDG
    {
        public string TENTK { get; set; }
        public string MADG { get; set; }
        public string MATKHAU { get; set; }
        public string ENCODE { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
