//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHLYHUY
    {
        public string MAPHIEU { get; set; }
        public string MASACH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<decimal> TIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
